name: Create Changelog
run-name: ${{ github.actor }} is generating a changelog
on: [push]
jobs:
  Create-Changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Changelog
        uses: ScottBrenner/generate-changelog-action@v1.3.3
        id: Changelog
        with:
          package-dir: 'client\package.json'

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false